<Project>
  <PropertyGroup>
    <ModRepoRoot>$(MSBuildThisFileDirectory)</ModRepoRoot>
    <IsRimWorldMod Condition="'$(IsRimWorldMod)' == ''">true</IsRimWorldMod>
    <RimWorldGameVersion Condition="'$(RimWorldGameVersion)' == ''">1.6</RimWorldGameVersion>
    <TargetFramework>net472</TargetFramework>
    <LangVersion Condition="'$(LangVersion)' == ''">latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo Condition="'$(GenerateAssemblyInfo)' == ''">false</GenerateAssemblyInfo>
    <RimWorldRoot Condition="'$(RimWorldRoot)' == ''">$(RIMWORLD_DIR)</RimWorldRoot>
    <RimWorldRoot Condition="'$(RimWorldRoot)' == ''">C:\Program Files (x86)\Steam\steamapps\common\RimWorld</RimWorldRoot>
    <RimWorldManaged Condition="'$(RimWorldManaged)' == ''">$(RimWorldRoot)\RimWorldWin64_Data\Managed</RimWorldManaged>
    <HarmonyDll Condition="'$(HarmonyDll)' == ''">$(HARMONY_DLL)</HarmonyDll>
    <HarmonyDll Condition="'$(HarmonyDll)' == ''">C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2009463077\Current\Assemblies\0Harmony.dll</HarmonyDll>
    <UnityModules Condition="'$(UnityModules)' == ''">CoreModule;IMGUIModule;TextRenderingModule;InputLegacyModule</UnityModules>
    <ModRepoRoot>$([MSBuild]::EnsureTrailingSlash('$(ModRepoRoot)'))</ModRepoRoot>
    <ModAssemblies Condition="'$(ModAssemblies)' == ''">$(ModRepoRoot)$(RimWorldGameVersion)\Assemblies\</ModAssemblies>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DebugType Condition="'$(DebugType)' == ''">full</DebugType>
    <DebugSymbols Condition="'$(DebugSymbols)' == ''">true</DebugSymbols>
    <Optimize Condition="'$(Optimize)' == ''">false</Optimize>
    <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' != 'Debug'">
    <DebugType Condition="'$(DebugType)' == ''">none</DebugType>
    <DebugSymbols Condition="'$(DebugSymbols)' == ''">false</DebugSymbols>
    <Optimize Condition="'$(Optimize)' == ''">true</Optimize>
    <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
  </PropertyGroup>
</Project>
